'use client';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, Bookmark, CalendarPlus, Clock3, Flame, Star } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Loading from '../../components/Loading';
import { useApp, Workout } from '../../contexts/AppContext';
const API='https://api.api-store.workers.dev/api/fitlog';
export default function Detail(){ const {id}=useParams<{id:string}>(); const [w,setW]=useState<Workout|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const {addToPlan,saveForLater,isInPlan,isSaved}=useApp();
 useEffect(()=>{fetch(`${API}/${id}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setW).catch(()=>setError(true)).finally(()=>setLoading(false))},[id]);
 if(loading)return <Loading/>; if(error||!w)return <div className="container py-20 text-center"><h1 className="display text-4xl">WORKOUT NOT FOUND</h1><Link href="/" className="lime-btn mt-5 inline-flex px-5 py-3 text-sm">Back to workouts</Link></div>;
 return <main className="container py-8"><Link href="/" className="mb-5 inline-flex items-center gap-2 text-xs text-[#9ca4ae] hover:text-white"><ArrowLeft size={14}/> Back to library</Link><div className="grid gap-8 lg:grid-cols-[1fr_1fr]"><div className="relative aspect-square overflow-hidden rounded-[14px] border border-[#252b34] bg-[#151a20]"><Image src={w.image} alt={w.name} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" priority/></div><div><h1 className="display text-4xl font-black uppercase leading-none sm:text-5xl">{w.name}</h1><p className="mt-4 text-sm leading-6 text-[#9da5b0]">{w.description}</p><div className="mt-4 flex flex-wrap gap-2">{w.muscleGroups.map(m=><span key={m} className="tag">{m}</span>)}</div><div className="card mt-6 overflow-hidden">{[['EQUIPMENT',w.equipment],['DIFFICULTY',w.difficulty],['SETS',String(w.sets)],['REPS',w.reps],['DURATION',`${w.duration} min`],['CALORIES',`${w.caloriesBurned} kcal`],['RATING',String(w.rating)]].map(([a,b])=><div key={a} className="flex items-center justify-between border-b border-[#252b34] px-5 py-4 text-xs last:border-b-0"><span className="text-[10px] font-bold tracking-wider text-[#8c95a1]">{a}</span><span>{b}</span></div>)}</div><h2 className="display mt-7 text-xl font-black">INSTRUCTIONS</h2><ol className="mt-3 space-y-3 text-sm text-[#b5bbc4]">{w.instructions.map((s,i)=><li key={s} className="flex gap-3"><span className="font-bold text-[#7e8792]">{i+1}.</span><span>{s}</span></li>)}</ol><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>addToPlan(w.id)} className="lime-btn inline-flex items-center gap-2 px-5 py-3 text-xs"><CalendarPlus size={15}/>{isInPlan(w.id)?'Already in plan':"Add to today's plan"}</button><button onClick={()=>saveForLater(w.id)} className="outline-btn inline-flex items-center gap-2 px-5 py-3 text-xs"><Bookmark size={15}/>{isSaved(w.id)?'Saved':'Save for later'}</button></div></div></div></main>;
}
