'use client';
import Link from 'next/link';
import Image from 'next/image';
import { Check, ChevronDown, Clock3, Flame, Star, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import Loading from '../components/Loading';
import { useApp, Workout } from '../contexts/AppContext';
const API='https://api.abcz.workers.dev/api/fitlog';
type Sort='duration'|'calories'|'rating';
export default function MyPlan(){ const [tab,setTab]=useState<'plan'|'saved'>('plan'); const [sort,setSort]=useState<Sort>('duration'); const [all,setAll]=useState<Workout[]>([]); const [loading,setLoading]=useState(true); const {plan,saved,done,removeFromPlan,removeSaved,markDone}=useApp();
 useEffect(()=>{fetch(API).then(r=>r.json()).then(setAll).finally(()=>setLoading(false)); const qs=new URLSearchParams(window.location.search); if(qs.get('tab')==='saved') setTab('saved');},[]);
 const source=tab==='plan'?plan:saved; const list=useMemo(()=>all.filter(w=>source.includes(w.id)).sort((a,b)=>sort==='duration'?a.duration-b.duration:sort==='calories'?a.caloriesBurned-b.caloriesBurned:b.rating-a.rating),[all,source,sort]);
 const metrics=useMemo(()=>{const p=all.filter(w=>plan.includes(w.id));return {count:p.length,minutes:p.reduce((s,w)=>s+w.duration,0),calories:p.reduce((s,w)=>s+w.caloriesBurned,0)}},[all,plan]);
 return <main className="container py-8"><h1 className="display text-4xl font-black uppercase">MY PLAN</h1><p className="mt-1 text-xs text-[#858e9a]">Cap of five lifts for today. Finish them, then load more.</p><div className="card mt-6 grid grid-cols-3 divide-x divide-[#252b34] px-5 py-5 sm:px-8"><Metric label="Exercises" value={metrics.count}/><Metric label="Minutes" value={metrics.minutes}/><Metric label="Calories" value={metrics.calories}/></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg border border-[#252b34] bg-[#11151b] p-1"><button onClick={()=>setTab('plan')} className={`rounded-md px-4 py-2 text-xs ${tab==='plan'?'bg-[#1d222a] font-bold text-white':'text-[#7f8895]'}`}>Today&apos;s Plan</button><button onClick={()=>setTab('saved')} className={`rounded-md px-4 py-2 text-xs ${tab==='saved'?'bg-[#1d222a] font-bold text-white':'text-[#7f8895]'}`}>Saved</button></div><label className="flex items-center gap-2 text-xs text-[#7f8895]">Sort By <span className="relative"><select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="appearance-none rounded-lg border border-[#2b323d] bg-[#11151b] py-2 pl-3 pr-8 text-xs text-white outline-none"><option value="duration">Duration</option><option value="calories">Calories</option><option value="rating">Rating</option></select><ChevronDown size={14} className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2"/></span></label></div>{loading?<Loading/>:list.length===0?<div className="mt-5 grid min-h-[300px] place-items-center rounded-xl border border-dashed border-[#252b34] text-center"><div><h2 className="display text-2xl font-black">NOTHING HERE YET</h2><p className="mt-2 text-xs text-[#858e9a]">Browse the library and add a lift to get today moving.</p><Link href="/" className="lime-btn mt-5 inline-flex px-5 py-3 text-xs">Go to workouts</Link></div></div>:<div className="mt-5 space-y-3">{list.map(w=><PlanRow key={w.id} w={w} isPlan={tab==='plan'} isDone={done.includes(w.id)} onRemove={()=>tab==='plan'?removeFromPlan(w.id):removeSaved(w.id)} onDone={()=>markDone(w.id)}/>)}</div>}</main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="px-3 first:pl-0 last:pr-0 sm:px-8"><p className="text-[10px] text-[#808895]">{label}</p><p className="display mt-1 text-3xl font-black text-white">{value}</p></div>}
function PlanRow({w,isPlan,isDone,onRemove,onDone}:{w:Workout;isPlan:boolean;isDone:boolean;onRemove:()=>void;onDone:()=>void}){return <div className="card flex flex-col gap-4 p-3 sm:flex-row sm:items-center sm:p-3"><div className="relative h-20 w-full shrink-0 overflow-hidden rounded-lg sm:w-32"><Image src={w.image} alt={w.name} fill sizes="128px" className="object-cover"/></div><div className="min-w-0 flex-1"><h3 className="display text-lg font-black uppercase">{w.name}</h3><p className="text-[11px] text-[#858e9a]">{w.equipment}</p><div className="mt-2 flex flex-wrap gap-3 text-[11px] text-[#b6bdc6]"><span className="flex items-center gap-1"><Clock3 className="stat-icon"/>{w.duration} min</span><span className="flex items-center gap-1"><Flame className="stat-icon"/>{w.caloriesBurned} kcal</span><span className="flex items-center gap-1"><Star className="stat-icon"/>{w.rating}</span></div></div><div className="flex flex-wrap items-center gap-2"><Link href={`/workouts/${w.id}`} className="outline-btn px-4 py-2 text-[11px]">View Details</Link>{isPlan&&<button onClick={onDone} disabled={isDone} className="lime-btn inline-flex items-center gap-1 px-4 py-2 text-[11px] disabled:opacity-50"><Check size={13}/>{isDone?'Done':'Mark as Done'}</button>}<button onClick={onRemove} className="grid h-9 w-9 place-items-center rounded-full text-[#858e9a] hover:bg-[#1b2027] hover:text-white" aria-label="Remove"><X size={16}/></button></div></div>}
